
package ru.itmo.webservices.lab1.standalone;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "AlbumWebService", targetNamespace = "http://standalone.lab1.webservices.itmo.ru/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface AlbumWebService {


    /**
     * @param albumName
     * @param singerId
     * @param genre
     * @param dateAdded
     * @param songsCount
     * @return returns java.util.List<ru.itmo.webservices.lab1.standalone.Album>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAlbums", targetNamespace = "http://standalone.lab1.webservices.itmo.ru/", className = "ru.itmo.webservices.lab1.standalone.GetAlbums")
    @ResponseWrapper(localName = "getAlbumsResponse", targetNamespace = "http://standalone.lab1.webservices.itmo.ru/", className = "ru.itmo.webservices.lab1.standalone.GetAlbumsResponse")
    @Action(input = "http://standalone.lab1.webservices.itmo.ru/AlbumWebService/getAlbumsRequest", output = "http://standalone.lab1.webservices.itmo.ru/AlbumWebService/getAlbumsResponse")
    public List<Album> getAlbums(
            @WebParam(name = "singerId", targetNamespace = "")
                    String singerId,
            @WebParam(name = "songsCount", targetNamespace = "")
                    Long songsCount,
            @WebParam(name = "albumName", targetNamespace = "")
                    String albumName,
            @WebParam(name = "genre", targetNamespace = "")
                    String genre,
            @WebParam(name = "dateAdded", targetNamespace = "")
                    Long dateAdded);

}
