
package ru.itmo.webservices.lab1.standalone;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AlbumsService", targetNamespace = "http://standalone.lab1.webservices.itmo.ru/", wsdlLocation = "http://localhost:8080/AlbumService?wsdl")
public class AlbumsService
    extends Service
{

    private final static URL ALBUMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ALBUMSSERVICE_EXCEPTION;
    private final static QName ALBUMSSERVICE_QNAME = new QName("http://standalone.lab1.webservices.itmo.ru/", "AlbumsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/AlbumService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALBUMSSERVICE_WSDL_LOCATION = url;
        ALBUMSSERVICE_EXCEPTION = e;
    }

    public AlbumsService() {
        super(__getWsdlLocation(), ALBUMSSERVICE_QNAME);
    }

    public AlbumsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALBUMSSERVICE_QNAME, features);
    }

    public AlbumsService(URL wsdlLocation) {
        super(wsdlLocation, ALBUMSSERVICE_QNAME);
    }

    public AlbumsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALBUMSSERVICE_QNAME, features);
    }

    public AlbumsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlbumsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlbumWebService
     */
    @WebEndpoint(name = "AlbumWebServicePort")
    public AlbumWebService getAlbumWebServicePort() {
        return super.getPort(new QName("http://standalone.lab1.webservices.itmo.ru/", "AlbumWebServicePort"), AlbumWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlbumWebService
     */
    @WebEndpoint(name = "AlbumWebServicePort")
    public AlbumWebService getAlbumWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://standalone.lab1.webservices.itmo.ru/", "AlbumWebServicePort"), AlbumWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALBUMSSERVICE_EXCEPTION!= null) {
            throw ALBUMSSERVICE_EXCEPTION;
        }
        return ALBUMSSERVICE_WSDL_LOCATION;
    }

}
